// Generated by CoffeeScript 1.6.3
(function() {
  var error, parse, parseBlock, parseTree;

  parseBlock = function() {};

  parseTree = function() {};

  parse = function() {};

  error = function() {};

  if (typeof define !== "undefined" && define !== null) {
    define({
      parse: parse,
      error: error
    });
  } else if (typeof exports !== "undefined" && exports !== null) {
    exports.parse = parse;
    exports.error = error;
  } else if (typeof window !== "undefined" && window !== null) {
    window.parse = parse;
    window.error = error;
  }

}).call(this);
