// Generated by CoffeeScript 1.6.3
var List, a, type;

type = require('./util').type;

List = (function() {
  function List(data) {
    this.data = data;
    if ((type(this.data)) === 'string') {
      this.data = this.data.split('');
    } else if ((type(this.data)) !== 'array') {
      throw new Error("wrong usage of List with `" + data + "`");
    }
  }

  return List;

})();

List.prototype.__defineGetter__('head', function() {
  return this.data[0];
});

List.prototype.__defineGetter__('init', function() {
  return this.data.slice(0, this.data.length - 1);
});

List.prototype.__defineGetter__('body', function() {
  return this.data.slice(1);
});

List.prototype.__defineGetter__('tail', function() {
  return this.data[this.data.length - 1];
});

exports.List = List;

a = new List('abc');

if (!module.parent) {
  console.log(a.head);
  console.log(a.init);
  console.log(a.body);
  console.log(a.tail);
}

/*
//@ sourceMappingURL=list.map
*/
