// Generated by CoffeeScript 1.6.3
var List, fs, match, parse, path, wrap_parse;

fs = require('fs');

path = require('path');

match = require('coffee-pattern').match;

List = require('./list').List;

parse = function(status, ast, text) {
  var default_token;
  match(text, null, default_token);
  return default_token = function() {};
};

wrap_parse = function(filename) {
  var ast, fullpath, text;
  fullpath = path.join(process.env.PWD, "./test/" + filename);
  text = fs.readFileSync(fullpath, 'utf8');
  return ast = {
    filename: filename,
    fullpath: fullpath,
    tree: parse([], {}, text)
  };
};

exports.parse = wrap_parse;

/*
//@ sourceMappingURL=parse.map
*/
