// Generated by CoffeeScript 1.4.0
var draw, file, fs, log, parse;

log = console.log;

fs = require('fs');

parse = require('./parser').parse;

draw = function(json) {
  return JSON.stringify(json, null, 2);
};

file = fs.readFileSync('../example/code.cr', 'utf8');

log('result:', draw((parse(file)).ast));
