// Generated by CoffeeScript 1.4.0
var display, draw, fs, log, parse, test_file;

log = console.log;

fs = require('fs');

parse = require('./parser').parse;

draw = function(json) {
  return JSON.stringify(json, null, 2);
};

test_file = '../example/code.cr';

(display = function() {
  var file;
  file = fs.readFileSync(test_file, 'utf8');
  return log('result:', draw((parse(file)).tree));
})();

fs.watchFile(test_file, {
  interval: 100
}, display);
