// Generated by CoffeeScript 1.6.3
var prettyjson;

prettyjson = require('prettyjson');

exports.type = function(x) {
  return Object.prototype.toString.call(x).slice(1, -1).split(' ')[1].toLowerCase();
};

exports.render = prettyjson.render;

exports.stringify = function(object) {
  return JSON.stringify(object, null, 2);
};

/*
//@ sourceMappingURL=util.map
*/
