// Generated by CoffeeScript 1.6.3
(function() {
  var q, source_file;

  source_file = "./cirru/indent.cr";

  q = function(query) {
    return document.querySelector(query);
  };

  define(function(require, exports) {
    var cirru, compact, handle, paint, req;
    cirru = require("cirru");
    compact = require("compact");
    req = new XMLHttpRequest;
    req.open("get", source_file);
    req.send();
    req.onload = function() {
      cirru.parse.compact = true;
      q("textarea.source").value = req.response;
      q("textarea.source").focus();
      return paint(req.response);
    };
    paint = function(text) {
      var res;
      console.clear();
      res = cirru.parse(text, source_file);
      compact.render.hide = true;
      return q("textarea.target").value = (compact.render(res)).trimRight();
    };
    q("textarea.source").onkeyup = function() {
      return paint(this.value);
    };
    handle = function(event) {
      var indent, last_line, new_text, start, text_after, text_before;
      console.log(event.keyCode);
      if (event.keyCode === 13) {
        event.preventDefault();
        start = this.selectionStart;
        text_before = this.value.slice(0, start);
        text_after = this.value.slice(start);
        last_line = text_before.split("\n").reverse()[0];
        indent = "";
        while (last_line[0] === " ") {
          indent += " ";
          last_line = last_line.slice(1);
        }
        new_text = text_before + "\n" + indent + text_after;
        this.value = new_text;
        return this.selectionStart = this.selectionEnd = start + indent.length + 1;
      } else if (event.keyCode === 9) {
        event.preventDefault();
        start = this.selectionStart;
        text_before = this.value.slice(0, start);
        text_after = this.value.slice(start);
        new_text = text_before + "  " + text_after;
        this.value = new_text;
        return this.selectionStart = this.selectionEnd = start + 2;
      }
    };
    q("textarea.source").onkeydown = handle;
    return q("textarea.target").onkeydown = handle;
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
