name: npm publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: yarn && yarn compile && yarn test

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
